# Generated by Django 4.0.4 on 2022-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_options_alter_employee_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('email', ''), _negated=True), name='email_not_empty'),
        ),
    ]
